version: '3.1'
services:
  memcached:
    image: 'memcached:alpine'
    container_name: php-docker-memcached
  redis:
    image: 'redis:alpine'
    container_name: php-docker-redis
  mariadb:
    image: 'mariadb:10.1'
    container_name: php-docker-mariadb
    working_dir: /application
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
    volumes:
      - './db-data:/var/lib/mysql'
      - './migration/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql'
      - >-
        ./migration/02_addLocation.sql:/docker-entrypoint-initdb.d/02_addLocation.sql
      - >-
        ./migration/03_addDummyData.sql:/docker-entrypoint-initdb.d/03_addDummyData.sql
  webserver:
    image: 'nginx:alpine'
    container_name: php-docker-webserver
    working_dir: /application
    volumes:
      - '.:/application'
      - './.phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:80'
  php-fpm:
    build: .phpdocker/php-fpm
    container_name: php-docker-php-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - >-
        ./.phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    ports:
      - '9000:9000'
    environment:
      - 'MYSQL_HOST=${MYSQL_HOST}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'PHP_ENV=${PHP_ENV}'
      - 'PHP_APP_LOCALE=${PHP_APP_LOCALE}'
      - 'WEBPACK_PORT=${WEBPACK_PORT}'
      - 'WEBPACK_APP_URL=${WEBPACK_APP_URL}'
      - 'APP_BASE_URL=${APP_BASE_URL}'
      - 'APP_ASSETS_URL=${APP_ASSETS_URL}'
